package com.nla.workflow.entity;

public enum MilestoneType {
    PROPOSAL_SUBMISSION,
    PROPOSAL_APPROVAL,
    PRELIMINARY_NOTIFICATION,
    FINAL_NOTIFICATION,
    AWARD_DECLARATION,
    COMPENSATION_DISBURSEMENT,
    POSSESSION_TAKEN,
    REHABILITATION_RESETTLEMENT,
    PROJECT_ACQUISITION_COMPLETION
}
