spring.application.name=National Land Acquisition & Management System (NLAMS)
server.port=${PORT:8080}

# Profiles
spring.profiles.active=postgres

# Neon PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-tiny-frost-b4fx87ki-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_gcPX8kledKS3

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway Database Migration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
app.upload.dir=uploads

# Logging
logging.level.com.nla=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN
