package com.nla.document.entity;

public enum DocumentType {
    PROJECT_PROPOSAL,
    SUPPORTING_DOCUMENT,
    LAND_RECORD_ROR,
    CADASTRAL_MAP,
    GAZETTE_NOTIFICATION,
    VALUATION_REPORT,
    AWARD_COPY,
    COMPENSATION_VOUCHER,
    PANCHNAMA_POSSESSION,
    FIELD_INSPECTION_PHOTO,
    RR_SURVEY_REPORT,
    RR_ALLOTMENT_LETTER,
    OTHER
}
